Fixes #16976 - add puppet env fact to spec helper
Katello/foreman-installer-modulesync pull request #10
Opened 2016-10-17 19:16 UTC by chris1984

2016-10-17 19:27 UTC, stbenjam requested changes
Otherwise OK

2016-10-17 19:27 UTC, stbenjam commented on moduleroot/spec/spec_helper.rb
> +add_custom_fact :puppet_environmentpath, Gem::Version.new(Puppet.version) >= Gem::Version.new('4.0') ? '/etc/puppetlabs/code/environments' : '/etc/puppet/environments' # added puppet env variable for
The comment should so the source of the fact, which is `puppetlabs-stdlib`

2016-10-17 20:11 UTC, chris1984 commented
@stbenjam ack fixed with adding puppetlabs-stdlib to the comment.

2016-10-17 21:32 UTC, stbenjam commented
Just `puppetlabs-stdlib`, please, it should be consistent with the other facts, the comment is acting as a column that only has the source of the fact

2016-10-17 22:10 UTC, chris1984 commented
@stbenjam no problem, i have adjusted it like the others # puppetlabs-stdlib

2016-10-17 22:24 UTC, stbenjam approved these changes

2016-10-17 22:24 UTC, stbenjam commented
Thanks! Looks ok to me, I'll test and sync the rest of the modules with this tomorrow hopefully

2016-10-17 22:29 UTC, chris1984 commented
@stbenjam cool thank you, once that gets pulled in I think it will help my other PR that is failing on the puppet 4 tests.

2016-10-18 14:32 UTC, stbenjam commented
Thanks, confirmed it fixes puppet-capsule: https://travis-ci.org/stbenjam/puppet-capsule/builds/168628514

2016-10-18 14:32 UTC, stbenjam commented
ACK

2016-10-18 14:32 UTC, merged

2016-10-18 14:43 UTC, ekohl commented
@stbenjam I see you created a lot of modulesync PRs. I can ACK them all individually but when the tests pass you can just merge them.

2016-10-18 15:01 UTC, stbenjam commented
@ehelms Went through and marked them all approved, I know it's always a bit of a hassle. Doesn't foreman just usually push to master?

2016-10-18 15:21 UTC, ekohl commented
It's not that often that we sync so there's no formal procedure. What I think I did the last time:
* Push all branches to your own forks
* Create PRs for each branch (```hub pull-request``` is what I use)
* Create a PR with a checklist linking to all the PRs
* Merge the individual PRs (checking them off in the modulesync PR)
* Merge the modulesync PR

I think this is at least partially scriptable but I haven't because it's not very often that this is done.